import { Product, Review } from './types';

const generatePriceHistory = (basePrice: number): { date: string; price: number }[] => {
  const history = [];
  for (let i = 30; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    // Fluctuate price by up to 5%
    const price = basePrice + (Math.random() - 0.5) * (basePrice * 0.1);
    history.push({
      date: date.toISOString().split('T')[0],
      price: Math.round(price),
    });
  }
  return history;
};

const mockReviews: Omit<Review, 'id' | 'date'>[] = [
    { author: 'Rohan Sharma', rating: 5, comment: 'Absolutely fantastic product! Exceeded my expectations.' },
    { author: 'Priya Patel', rating: 4, comment: 'Very good quality, but the delivery was a bit slow.' },
    { author: 'Amit Singh', rating: 5, comment: 'Worth every penny. I would highly recommend this to anyone.' },
    { author: 'Sneha Gupta', rating: 3, comment: 'It\'s okay. Does the job but nothing special.' },
    { author: 'Vijay Kumar', rating: 4, comment: 'Solid build quality and works as described. Happy with my purchase.' },
    { author: 'Anjali Desai', rating: 5, comment: 'Amazing! I use it every day. A must-have.' },
];

const generateMockReviews = (): Review[] => {
    const reviews = [];
    const reviewCount = Math.floor(Math.random() * 4) + 2; // 2 to 5 reviews
    const usedReviews = new Set();

    for (let i = 0; i < reviewCount; i++) {
        let reviewIndex = Math.floor(Math.random() * mockReviews.length);
        while (usedReviews.has(reviewIndex)) {
            reviewIndex = Math.floor(Math.random() * mockReviews.length);
        }
        usedReviews.add(reviewIndex);

        const date = new Date();
        date.setDate(date.getDate() - Math.floor(Math.random() * 30)); // Review from last 30 days

        reviews.push({
            id: Date.now() + i,
            ...mockReviews[reviewIndex],
            date: date.toISOString().split('T')[0],
        });
    }
    return reviews.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};


export const products: Product[] = [
  // Electronics
  {
    id: 1,
    name: 'Echo Dot (4th Gen)',
    description: 'Smart speaker with Alexa. Control your music, smart home devices, and get answers to your questions with just your voice.',
    price: 4499,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61KIy6gX-CL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(4499),
    reviews: generateMockReviews(),
  },
  {
    id: 5,
    name: 'boAt Airdopes 141',
    description: 'True Wireless Earbuds with 42H Playtime, ENx™ Tech, and IWP™. IPX4 water resistance makes them perfect for workouts.',
    price: 1299,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1299),
    reviews: generateMockReviews(),
  },
  {
    id: 8,
    name: 'HP 15s Laptop',
    description: '11th Gen Intel Core i3, 8GB RAM, 512GB SSD, 15.6-inch FHD Display. A reliable laptop for everyday work and entertainment.',
    price: 38990,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(38990),
    reviews: generateMockReviews(),
  },
  {
    id: 11,
    name: 'MI 32-inch A Series HD Smart TV',
    description: 'A feature-packed smart TV with HD Ready display, Google TV, Dolby Audio, and a sleek, bezel-less design.',
    price: 13999,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(13999),
    reviews: generateMockReviews(),
  },
  {
    id: 17,
    name: 'Logitech B170 Wireless Mouse',
    description: 'Reliable 2.4 GHz wireless mouse with USB nano receiver. Ambidextrous design and 12-months battery life.',
    price: 595,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(595),
    reviews: generateMockReviews(),
  },
  {
    id: 21,
    name: 'Sony WH-1000XM4 Wireless Headphones',
    description: 'Industry-leading noise canceling headphones with a 30-hour battery life and touch sensor controls.',
    price: 24990,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(24990),
    reviews: generateMockReviews(),
  },
  {
    id: 22,
    name: 'SanDisk Ultra 128GB MicroSD Card',
    description: 'Class 10 memory card with read speeds up to 120MB/s for mobile devices. Comes with an SD adapter.',
    price: 949,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61AJdYvf2qL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(949),
    reviews: generateMockReviews(),
  },
  {
    id: 23,
    name: 'JBL Flip 5 Wireless Speaker',
    description: 'Powerful portable Bluetooth speaker with waterproof design. Delivers surprisingly powerful stereo sound.',
    price: 6999,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61d0gOkNCCL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(6999),
    reviews: generateMockReviews(),
  },
  {
    id: 45,
    name: 'Canon EOS 1500D DSLR Camera',
    description: '24.1MP DSLR with EF S18-55 is II Lens, WiFi, and NFC. Perfect for beginners.',
    price: 38499,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(38499),
    reviews: generateMockReviews(),
  },
  {
    id: 46,
    name: 'Wipro 16A Wi-Fi Smart Plug',
    description: 'Control heavy appliances like ACs, geysers from anywhere with the Wipro Smart Home App.',
    price: 899,
    category: 'Electronics',
    image: 'https://m.media-amazon.com/images/I/61wEa8n5zCL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(899),
    reviews: generateMockReviews(),
  },
  // Mobiles
  {
    id: 2,
    name: 'OnePlus Nord CE 3 Lite 5G',
    description: 'A powerful mid-range smartphone with a 108MP main camera, 67W SUPERVOOC charging, and a smooth 120Hz display.',
    price: 19999,
    category: 'Mobiles',
    image: 'https://m.media-amazon.com/images/I/61LB+d0vheL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(19999),
    reviews: generateMockReviews(),
  },
  {
    id: 14,
    name: 'Fire-Boltt Ninja Call Pro Smart Watch',
    description: 'Dual Chip Bluetooth Calling watch with 1.69" HD Display, 100 sports modes, and health tracking features.',
    price: 1799,
    category: 'Mobiles',
    image: 'https://m.media-amazon.com/images/I/61S9aVnrzjL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1799),
    reviews: generateMockReviews(),
  },
  {
    id: 18,
    name: 'Samsung Galaxy S23 FE 5G',
    description: 'Flagship-level smartphone with a pro-grade camera, stunning display, and powerful performance. (Mint, 8GB, 128GB)',
    price: 54999,
    category: 'Mobiles',
    image: 'https://m.media-amazon.com/images/I/61J4Z2i2VjL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(54999),
    reviews: generateMockReviews(),
  },
  {
    id: 24,
    name: 'Apple iPhone 14 (128GB)',
    description: 'Features a 6.1-inch Super Retina XDR display, A15 Bionic chip, advanced camera system, and incredible battery life.',
    price: 69900,
    category: 'Mobiles',
    image: 'https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(69900),
    reviews: generateMockReviews(),
  },
  {
    id: 25,
    name: 'Redmi 12C (4GB RAM, 64GB)',
    description: 'Budget-friendly smartphone with a large display, 50MP AI dual camera, and a massive 5000mAh battery.',
    price: 8999,
    category: 'Mobiles',
    image: 'https://m.media-amazon.com/images/I/61TE7ITqKdL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(8999),
    reviews: generateMockReviews(),
  },
  // Home & Kitchen
  {
    id: 3,
    name: 'Samsung 253L Refrigerator',
    description: '3 Star with Inverter. Double Door Refrigerator with Convertible 3-in-1 technology for optimal storage.',
    price: 24990,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71OxJeynwSL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(24990),
    reviews: generateMockReviews(),
  },
  {
    id: 7,
    name: 'Prestige Iris 750W Mixer Grinder',
    description: 'Powerful 750 watt motor with 3 stainless steel jars and 1 juicer jar. Perfect for all your grinding and blending needs.',
    price: 3299,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(3299),
    reviews: generateMockReviews(),
  },
  {
    id: 13,
    name: 'Philips Steam Iron GC1905',
    description: '1440-Watt Steam Iron with Spray. American Heritage Black Linished soleplate for easy gliding on all fabrics.',
    price: 1599,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1599),
    reviews: generateMockReviews(),
  },
  {
    id: 15,
    name: 'Solimo 1000-TC Bedsheet',
    description: 'Amazon Brand - Solimo premium 100% cotton double bedsheet with 2 pillow covers. Soft and breathable.',
    price: 1999,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1999),
    reviews: generateMockReviews(),
  },
  {
    id: 20,
    name: 'KENT Supreme RO Water Purifier',
    description: 'RO+UF+TDS Control water purifier. Multiple purification process ensures 100% pure drinking water.',
    price: 14499,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/61wEa8n5zCL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(14499),
    reviews: generateMockReviews(),
  },
  {
    id: 26,
    name: 'Philips Air Fryer HD9200/90',
    description: 'Uses up to 90% less fat. Fry, bake, grill, roast and even reheat. With Rapid Air Technology for healthy frying.',
    price: 8499,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(8499),
    reviews: generateMockReviews(),
  },
  {
    id: 27,
    name: 'Wakefit Orthopedic Memory Foam Mattress',
    description: '72x36x6 inches single size mattress. Provides excellent back support and a comfortable sleep experience.',
    price: 7500,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71OxJeynwSL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(7500),
    reviews: generateMockReviews(),
  },
  {
    id: 28,
    name: 'LG 1.5 Ton 5 Star AI DUAL Inverter Split AC',
    description: 'Energy-efficient air conditioner with AI convertible 6-in-1 cooling and anti-virus protection.',
    price: 46990,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(46990),
    reviews: generateMockReviews(),
  },
  {
    id: 47,
    name: 'Borosil Glass Lunch Box Set of 3',
    description: 'Microwave-safe glass tiffin box set with leak-proof lids and a carry bag.',
    price: 1399,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1399),
    reviews: generateMockReviews(),
  },
  {
    id: 66,
    name: 'Espresso Coffee Machine',
    description: '15-bar pressure pump to create rich, aromatic espresso shots. Includes a milk frother for cappuccinos.',
    price: 9999,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/61KIy6gX-CL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(9999),
    reviews: generateMockReviews(),
  },
  {
    id: 67,
    name: 'Robotic Vacuum Cleaner',
    description: 'Smart vacuum with Wi-Fi connectivity, app control, and intelligent pathfinding for automated cleaning.',
    price: 16999,
    category: 'Home & Kitchen',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(16999),
    reviews: generateMockReviews(),
  },
  // Books
  {
    id: 4,
    name: 'The Psychology of Money',
    description: 'A timeless book by Morgan Housel offering lessons on wealth, greed, and happiness.',
    price: 350,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(350),
    reviews: generateMockReviews(),
  },
  {
    id: 10,
    name: 'Atomic Habits',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear. An international bestseller.',
    price: 499,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/81F90H7hnML._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(499),
    reviews: generateMockReviews(),
  },
  {
    id: 16,
    name: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    description: 'Discover the Japanese secret to a long and happy life with this international bestseller.',
    price: 320,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/81l3rZK4lnL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(320),
    reviews: generateMockReviews(),
  },
  {
    id: 29,
    name: 'Rich Dad Poor Dad',
    description: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not! By Robert T. Kiyosaki.',
    price: 410,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/81BE7eeKzAL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(410),
    reviews: generateMockReviews(),
  },
  {
    id: 30,
    name: 'The Alchemist',
    description: 'A classic novel by Paulo Coelho about following your dreams. A magical story that has inspired millions.',
    price: 250,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(250),
    reviews: generateMockReviews(),
  },
  {
    id: 50,
    name: 'Sapiens: A Brief History of Humankind',
    description: 'A thought-provoking book by Yuval Noah Harari that explores the history of the human species.',
    price: 450,
    category: 'Books',
    image: 'https://m.media-amazon.com/images/I/713jIoMO3UL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(450),
    reviews: generateMockReviews(),
  },
  // Fashion
  {
    id: 6,
    name: 'Levi\'s Men\'s 512 Slim Tapered Jeans',
    description: 'Classic Levi\'s style with a modern slim fit. Made with high-quality denim for comfort and durability.',
    price: 2100,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/jeans/600/400',
    priceHistory: generatePriceHistory(2100),
    reviews: generateMockReviews(),
  },
  {
    id: 9,
    name: 'Puma Men\'s Sneakers',
    description: 'Stylish and comfortable sneakers from Puma. Features a durable rubber sole and a breathable upper.',
    price: 1999,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/shoes/600/400',
    priceHistory: generatePriceHistory(1999),
    reviews: generateMockReviews(),
  },
  {
    id: 12,
    name: 'American Tourister 32L Backpack',
    description: 'A spacious and durable backpack, perfect for school, college, or short trips.',
    price: 1199,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/bag/600/400',
    priceHistory: generatePriceHistory(1199),
    reviews: generateMockReviews(),
  },
  {
    id: 19,
    name: 'Fastrack Men\'s Sunglasses',
    description: 'Stylish 100% UV protected sunglasses for men. Lightweight and comfortable for all-day wear.',
    price: 899,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/sunglasses/600/400',
    priceHistory: generatePriceHistory(899),
    reviews: generateMockReviews(),
  },
  {
    id: 31,
    name: 'Titan Neo Analog Watch for Men',
    description: 'A sophisticated analog watch with a leather strap and a date function. Water-resistant and durable.',
    price: 5495,
    category: 'Fashion',
    image: 'https://m.media-amazon.com/images/I/81a4mQf8YOL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(5495),
    reviews: generateMockReviews(),
  },
  {
    id: 32,
    name: 'Allen Solly Men\'s Polo Shirt',
    description: 'A classic fit polo shirt made from comfortable cotton fabric. Perfect for casual and semi-formal occasions.',
    price: 899,
    category: 'Fashion',
    image: 'https://m.media-amazon.com/images/I/71p4ev7VJvL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(899),
    reviews: generateMockReviews(),
  },
  {
    id: 48,
    name: 'Casio G-Shock Analog-Digital Watch',
    description: 'A rugged and shock-resistant watch with multiple features, perfect for an active lifestyle.',
    price: 9995,
    category: 'Fashion',
    image: 'https://m.media-amazon.com/images/I/61SapI0dvVL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(9995),
    reviews: generateMockReviews(),
  },
  {
    id: 68,
    name: 'Genuine Leather Wallet for Men',
    description: 'A sleek and durable wallet with multiple card slots, an ID window, and RFID blocking technology.',
    price: 799,
    category: 'Fashion',
    image: 'https://m.media-amazon.com/images/I/71r69Y7BSeL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(799),
    reviews: generateMockReviews(),
  },
  // Sports & Fitness
  {
    id: 33,
    name: 'Boldfit Yoga Mat for Men and Women',
    description: '6mm thick TPE material yoga mat with anti-slip feature. Comes with a carrying strap.',
    price: 1599,
    category: 'Sports & Fitness',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1599),
    reviews: generateMockReviews(),
  },
  {
    id: 34,
    name: 'Cockatoo 20kg Dumbbell Set',
    description: 'Adjustable PVC dumbbell set for home gym workouts. Includes rods and plates.',
    price: 1499,
    category: 'Sports & Fitness',
    image: 'https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1499),
    reviews: generateMockReviews(),
  },
  {
    id: 35,
    name: 'Optimum Nutrition (ON) Gold Standard 100% Whey Protein',
    description: '2.27 kg tub of Double Rich Chocolate whey protein. Helps build and maintain muscle.',
    price: 6899,
    category: 'Sports & Fitness',
    image: 'https://m.media-amazon.com/images/I/61KIy6gX-CL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(6899),
    reviews: generateMockReviews(),
  },
  {
    id: 36,
    name: 'Nivia Storm Football - Size 5',
    description: 'High-quality football suitable for training and matches on grass and artificial turf.',
    price: 449,
    category: 'Sports & Fitness',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(449),
    reviews: generateMockReviews(),
  },
  {
    id: 49,
    name: 'Yonex GR 303 Badminton Racquet Set',
    description: 'Set of 2 badminton racquets with full covers. Lightweight and durable for recreational play.',
    price: 999,
    category: 'Sports & Fitness',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(999),
    reviews: generateMockReviews(),
  },
  // Beauty & Personal Care
  {
    id: 37,
    name: 'NIVEA Men Face Wash, Deep Impact',
    description: '100g tube. Intense clean face wash with black carbon that gives a fresh feeling.',
    price: 199,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(199),
    reviews: generateMockReviews(),
  },
  {
    id: 38,
    name: 'Philips BT3231/15 Beard Trimmer',
    description: 'Cordless trimmer with 20 length settings, fast charge, and DuraPower technology for longer battery life.',
    price: 1549,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/81F90H7hnML._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1549),
    reviews: generateMockReviews(),
  },
  {
    id: 39,
    name: 'Cetaphil Moisturising Cream',
    description: '80g cream for face & body. Long-lasting hydration for dry, sensitive skin.',
    price: 450,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/81l3rZK4lnL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(450),
    reviews: generateMockReviews(),
  },
  {
    id: 40,
    name: 'The Man Company Perfume for Men',
    description: '100ml Eau De Parfum. Premium long-lasting fragrance with notes of citrus and wood.',
    price: 799,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/81BE7eeKzAL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(799),
    reviews: generateMockReviews(),
  },
  {
    id: 41,
    name: 'Dyson Airwrap Hair Styler',
    description: 'Complete multi-styler to curl, shape, smooth, and hide flyaways with no extreme heat.',
    price: 44900,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(44900),
    reviews: generateMockReviews(),
  },
  {
    id: 51,
    name: 'Mamaearth Onion Hair Oil',
    description: '150ml bottle for hair fall control and hair growth. Enriched with Redensyl.',
    price: 399,
    category: 'Beauty & Personal Care',
    image: 'https://m.media-amazon.com/images/I/713jIoMO3UL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(399),
    reviews: generateMockReviews(),
  },
  // Toys & Games
  {
    id: 42,
    name: 'LEGO Classic Large Creative Brick Box',
    description: '790 pieces of LEGO bricks in 33 different colors. Encourages open-ended creativity.',
    price: 3499,
    category: 'Toys & Games',
    image: 'https://m.media-amazon.com/images/I/81a4mQf8YOL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(3499),
    reviews: generateMockReviews(),
  },
  {
    id: 43,
    name: 'Monopoly Classic Board Game',
    description: 'The classic fast-dealing property trading game. Fun for the whole family.',
    price: 799,
    category: 'Toys & Games',
    image: 'https://m.media-amazon.com/images/I/71p4ev7VJvL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(799),
    reviews: generateMockReviews(),
  },
  {
    id: 44,
    name: 'Hot Wheels 10-Car Pack',
    description: 'Assortment of 10 different 1:64 scale Hot Wheels cars. Styles may vary.',
    price: 999,
    category: 'Toys & Games',
    image: 'https://m.media-amazon.com/images/I/61SapI0dvVL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(999),
    reviews: generateMockReviews(),
  },
  // Smart Home
  {
    id: 52,
    name: 'Smart Wi-Fi Door Lock',
    description: 'Keyless entry with fingerprint, app control, and numeric passcode. Get alerts on your phone.',
    price: 8999,
    category: 'Smart Home',
    image: 'https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(8999),
    reviews: generateMockReviews(),
  },
  {
    id: 53,
    name: 'Video Doorbell Pro',
    description: 'See, hear, and speak to visitors from anywhere. Features 1080p HD video and two-way talk.',
    price: 12500,
    category: 'Smart Home',
    image: 'https://m.media-amazon.com/images/I/61KIy6gX-CL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(12500),
    reviews: generateMockReviews(),
  },
  {
    id: 54,
    name: 'Smart LED Lighting Kit',
    description: 'Set of 3 smart bulbs and a hub. Control colors and brightness with your voice or an app.',
    price: 4999,
    category: 'Smart Home',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(4999),
    reviews: generateMockReviews(),
  },
  // Outdoor Gear
  {
    id: 55,
    name: '4-Person Camping Tent',
    description: 'Waterproof and easy-to-setup dome tent, perfect for family camping trips and outdoor adventures.',
    price: 4599,
    category: 'Outdoor Gear',
    image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(4599),
    reviews: generateMockReviews(),
  },
  {
    id: 56,
    name: '60L Hiking Backpack',
    description: 'Durable and spacious rucksack with multiple compartments and ergonomic support for long treks.',
    price: 3299,
    category: 'Outdoor Gear',
    image: 'https://m.media-amazon.com/images/I/61wEa8n5zCL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(3299),
    reviews: generateMockReviews(),
  },
  {
    id: 57,
    name: 'Portable Camping Stove',
    description: 'Compact and lightweight single-burner stove, ideal for cooking meals on the go.',
    price: 1899,
    category: 'Outdoor Gear',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(1899),
    reviews: generateMockReviews(),
  },
  // Tools
  {
    id: 58,
    name: 'Cordless Drill Driver Kit',
    description: '18V cordless drill with two batteries, a charger, and a set of drill bits. For DIY and professional use.',
    price: 5499,
    category: 'Tools',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(5499),
    reviews: generateMockReviews(),
  },
  {
    id: 59,
    name: '108-Piece Home Tool Kit',
    description: 'Comprehensive set of tools for home repairs, including screwdrivers, pliers, a hammer, and more.',
    price: 2199,
    category: 'Tools',
    image: 'https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(2199),
    reviews: generateMockReviews(),
  },
  {
    id: 60,
    name: 'Laser Distance Measure',
    description: 'Measure distances up to 50 meters with high precision. Features area and volume calculation.',
    price: 2999,
    category: 'Tools',
    image: 'https://m.media-amazon.com/images/I/61KIy6gX-CL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(2999),
    reviews: generateMockReviews(),
  },
  // Office Supplies
  {
    id: 61,
    name: 'Ergonomic Mesh Office Chair',
    description: 'High-back chair with lumbar support, adjustable armrests, and a breathable mesh design for comfort.',
    price: 8999,
    category: 'Office Supplies',
    image: 'https://m.media-amazon.com/images/I/61wEa8n5zCL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(8999),
    reviews: generateMockReviews(),
  },
  {
    id: 62,
    name: 'Adjustable Standing Desk',
    description: 'Electric height-adjustable desk to switch between sitting and standing. Improves posture and productivity.',
    price: 17990,
    category: 'Office Supplies',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(17990),
    reviews: generateMockReviews(),
  },
  {
    id: 63,
    name: 'Logitech MX Mechanical Keyboard',
    description: 'A high-performance mechanical keyboard with tactile quiet switches, smart illumination, and USB-C.',
    price: 15495,
    category: 'Office Supplies',
    image: 'https://m.media-amazon.com/images/I/71OxJeynwSL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(15495),
    reviews: generateMockReviews(),
  },
  // Gaming
  {
    id: 64,
    name: 'Razer DeathAdder V2 Gaming Mouse',
    description: 'Ergonomic gaming mouse with a 20K DPI optical sensor and 8 programmable buttons.',
    price: 3499,
    category: 'Gaming',
    image: 'https://m.media-amazon.com/images/I/61o2urRx0rL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(3499),
    reviews: generateMockReviews(),
  },
  {
    id: 65,
    name: 'HyperX Cloud II Gaming Headset',
    description: '7.1 surround sound headset with memory foam ear pads for ultimate comfort during long gaming sessions.',
    price: 7499,
    category: 'Gaming',
    image: 'https://m.media-amazon.com/images/I/71h4oHh4LDL._AC_SL1500_.jpg',
    priceHistory: generatePriceHistory(7499),
    reviews: generateMockReviews(),
  }
];


export const categories = ['All', ...Array.from(new Set(products.map(p => p.category)))];